#!/usr/bin/env bash

# Stops postgres using pg_ctl.
#
# Pass '-q' option if you don't want it to complain when it thinks postgres is not running.

set -e

if ps -x -o command | grep '[/]bin/postgres -D' >/dev/null; then
  echo "${0}: Stopping postgres"
  eval "$(ps -x -o command | grep '[/]bin/postgres -D' | sed 's/bin\/postgres/bin\/pg_ctl/') stop"
  echo ""
else
  if [[ $1 != "-q" ]]; then
    echo "${0}: Postgres does not seem to be running"
    exit 1
  fi
fi
